import { PrismaClient } from '@prisma/client';
import { PrismaLibSQL } from '@prisma/adapter-libsql';
import { readFileSync } from 'fs';

const adapter = new PrismaLibSQL({
  url: 'libsql://canadianwaterwaysexplorer-bterhart.aws-us-east-2.turso.io',
  authToken: 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzExMDYzODEsImlkIjoiMTliZDYzMmMtZjNkYy00YzAwLTg0ODItNzU5YjQ3MmIxMGE0IiwicmlkIjoiZTdiMjljMTYtNGJhZi00YzM3LWEyYzQtZjJmYmViYTcyMjA2In0.Mixg_E1goZM8e0_81rnymYLtKVBbsp3DhQgkKZ4eP0ONcm-oBnRDiZ8dPDHdjUAmg023zpBCoB0d832JlVHPDQ',
});
const prisma = new PrismaClient({ adapter });

interface MigrationEntry {
  place_id: string;
  name: string;
  url: string;
  note: string;
}

async function main() {
  // Load migration map generated by Python analysis
  const map: MigrationEntry[] = JSON.parse(readFileSync('/tmp/image_migration_map.json', 'utf-8'));
  console.log(`Migration map loaded: ${map.length} entries\n`);

  // Pre-fetch all Location and Waterway IDs so we can route each update
  const locationIds = new Set(
    (await prisma.location.findMany({ select: { id: true } })).map(l => l.id)
  );
  const waterwayIds = new Set(
    (await prisma.waterway.findMany({ select: { id: true } })).map(w => w.id)
  );
  console.log(`DB: ${locationIds.size} locations, ${waterwayIds.size} waterways\n`);

  let updatedLocations = 0;
  let updatedWaterways = 0;
  let errors = 0;

  for (const entry of map) {
    const { place_id, name, url, note } = entry;

    try {
      if (locationIds.has(place_id)) {
        await prisma.location.update({
          where: { id: place_id },
          data: { imageUrl: url },
        });
        updatedLocations++;
        console.log(`[LOC] ${name.padEnd(45)} ${note}`);
      } else if (waterwayIds.has(place_id)) {
        await prisma.waterway.update({
          where: { id: place_id },
          data: { imageUrl: url },
        });
        updatedWaterways++;
        console.log(`[WAY] ${name.padEnd(45)} ${note}`);
      } else {
        console.error(`[ERR] ID not found in either table: ${place_id} (${name})`);
        errors++;
      }
    } catch (err: any) {
      console.error(`[ERR] Failed to update ${place_id} (${name}): ${err.message}`);
      errors++;
    }
  }

  console.log(`\n========== MIGRATION COMPLETE ==========`);
  console.log(`  Locations updated : ${updatedLocations}`);
  console.log(`  Waterways updated : ${updatedWaterways}`);
  console.log(`  Total updated     : ${updatedLocations + updatedWaterways}`);
  console.log(`  Errors            : ${errors}`);
  console.log(`  Skipped (Marble Island): 1 — retained existing imageUrl (no usable image in CSV)`);
}

main().catch(console.error).finally(() => process.exit(0));
