// Comprehensive seed file for Indigenous Words - 200+ entries
// Includes conversational phrases and expanded vocabulary across language families

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Language family classification
const LANGUAGE_FAMILIES = {
  ALGONQUIN: "Algonquin/Algonquian",
  ATHAPASKAN: "Athapaskan/Dene",
  IROQUOIAN: "Iroquoian",
  ESKIMO_ALEUT: "Eskimo-Aleut",
} as const;

interface IndigenousWordData {
  word: string;
  translation: string;
  language: string;
  phonetic: string;
  meaning: string;
  culturalContext: string;
  category: string;
  languageFamily?: string;
  linguisticNotes?: string;
}

async function seedExpandedIndigenousWords() {
  console.log("Seeding expanded Indigenous words (target: 200+ words)...\n");

  const words: IndigenousWordData[] = [
    // ==================== CREE - PLAINS, WOODS, SWAMPY (ALGONQUIN FAMILY) ====================
    // Target: 50+ entries

    // CONVERSATIONAL PHRASES - CREE
    {
      word: "tanisi",
      translation: "hello / how are you",
      language: "Cree",
      phonetic: "TAN-ih-see",
      meaning: "A greeting meaning 'hello' or 'how are you?' - one of the most common phrases",
      culturalContext: "The standard Cree greeting. Often followed by asking about someone's wellbeing and family.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Used across Plains, Woods, and Swampy Cree dialects with slight pronunciation variations.",
    },
    {
      word: "kinanaskomitin",
      translation: "thank you",
      language: "Cree",
      phonetic: "kin-an-as-KOM-it-in",
      meaning: "Thank you - expressing gratitude",
      culturalContext: "An important phrase showing respect and appreciation. Gratitude is highly valued in Cree culture.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Literally means 'I am grateful to you'. More formal than casual thanks.",
    },
    {
      word: "ekosi",
      translation: "okay / that's all / goodbye",
      language: "Cree",
      phonetic: "ay-KO-see",
      meaning: "That's all, okay, or goodbye - used to conclude conversations",
      culturalContext: "A versatile word used to agree, conclude, or say goodbye. Shows conversational finality.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Functions as discourse marker. Common way to end phone calls or conversations.",
    },
    {
      word: "ehe",
      translation: "yes",
      language: "Cree",
      phonetic: "EH-heh",
      meaning: "Yes - affirmative response",
      culturalContext: "Simple affirmative. Often accompanied by a nod.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Ojibwe 'eya'. Common Algonquin affirmative pattern.",
    },
    {
      word: "namoya",
      translation: "no",
      language: "Cree",
      phonetic: "NAM-oh-ya",
      meaning: "No - negative response",
      culturalContext: "Simple negative. Can also mean 'not' in sentences.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "The negative particle in Cree. Used to negate verbs and nouns.",
    },
    {
      word: "peyakwan",
      translation: "please / same / likewise",
      language: "Cree",
      phonetic: "pay-YAK-wan",
      meaning: "Please, same, or likewise - polite request or agreement",
      culturalContext: "Shows politeness in requests. Also means 'it's the same' or 'likewise'.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "From peyak (one) + -wan (manner). Implies unity of thought.",
    },
    {
      word: "nitisiyihkason",
      translation: "my name is...",
      language: "Cree",
      phonetic: "nit-is-ee-YIH-ka-son",
      meaning: "My name is called... - how to introduce yourself",
      culturalContext: "Used for self-introduction. Names were very important and sometimes changed throughout life.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "From isiyihkason (to be called/named). The nit- prefix indicates first person.",
    },
    {
      word: "kikway kitisiyihkason",
      translation: "what is your name?",
      language: "Cree",
      phonetic: "KIK-way kit-is-ee-YIH-ka-son",
      meaning: "What are you called? - asking someone's name",
      culturalContext: "Polite way to ask someone's name. Shows interest in the person.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Kikway means 'what'. Kit- is the second person prefix.",
    },
    {
      word: "nitotema",
      translation: "my friend",
      language: "Cree",
      phonetic: "nit-OH-tem-ah",
      meaning: "My friend - term of endearment and relationship",
      culturalContext: "Friendship is sacred in Cree culture. Calling someone friend implies deep respect.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Root otema means friend/companion. Related to totem/kinship concepts.",
    },
    {
      word: "petakwan",
      translation: "come in / welcome",
      language: "Cree",
      phonetic: "pet-AK-wan",
      meaning: "Come inside - welcoming someone into your home",
      culturalContext: "Hospitality is fundamental to Cree culture. Guests are always welcomed and fed.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Imperative form meaning 'enter'. Cree hospitality was noted by early traders.",
    },
    {
      word: "waciye",
      translation: "hello / greetings",
      language: "Cree",
      phonetic: "wah-CHEE-yay",
      meaning: "Hello or greetings - informal greeting",
      culturalContext: "A more casual greeting than tanisi. Often used among friends.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Variant forms include 'wachiya'. Common in northern Cree dialects.",
    },
    {
      word: "mino kisikaw",
      translation: "good day / good morning",
      language: "Cree",
      phonetic: "MIN-oh KIS-ik-aw",
      meaning: "Good day - greeting used in the morning or daytime",
      culturalContext: "A pleasant greeting acknowledging the day. Reflects positive outlook.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Mino means 'good'. Kisikaw means 'day'. Similar pattern to other greetings.",
    },
    {
      word: "mino tipiskaw",
      translation: "good evening / good night",
      language: "Cree",
      phonetic: "MIN-oh tip-IS-kaw",
      meaning: "Good evening or good night greeting",
      culturalContext: "Evening greeting. Tipiskaw refers to night or darkness.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Tipiskaw means night. Mino tipiskaw is polite evening greeting.",
    },
    {
      word: "tanta",
      translation: "where",
      language: "Cree",
      phonetic: "TAN-ta",
      meaning: "Where - interrogative for location",
      culturalContext: "Used to ask about locations. Important for navigation and finding people.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Question word. Tanta + noun asks 'where is [noun]?'",
    },
    {
      word: "tanta ohci",
      translation: "where from",
      language: "Cree",
      phonetic: "TAN-ta OH-chi",
      meaning: "Where from - asking someone's origin",
      culturalContext: "Asking about homeland. Territory and place are important to identity.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Ohci indicates origin or source. Common question when meeting someone.",
    },

    // NUMBERS - CREE
    {
      word: "peyak",
      translation: "one (1)",
      language: "Cree",
      phonetic: "PAY-yak",
      meaning: "The number one",
      culturalContext: "First number in Cree counting system. Also means 'alone' or 'single'.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'bezhig'. Proto-Algonquian *nekotwi.",
    },
    {
      word: "niso",
      translation: "two (2)",
      language: "Cree",
      phonetic: "NIS-oh",
      meaning: "The number two",
      culturalContext: "Second number. Duality is significant in many Indigenous worldviews.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'niizh'. Common Algonquin root for two.",
    },
    {
      word: "nisto",
      translation: "three (3)",
      language: "Cree",
      phonetic: "NIS-toh",
      meaning: "The number three",
      culturalContext: "Third number. Three is often significant in ceremonies and stories.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'niswi'. Proto-Algonquian *neswa.",
    },
    {
      word: "newo",
      translation: "four (4)",
      language: "Cree",
      phonetic: "NAY-woh",
      meaning: "The number four - sacred number representing the four directions",
      culturalContext: "Four is sacred, representing the four directions, seasons, and elements. Central to ceremonies.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Four is spiritually significant. Four directions central to worldview.",
    },
    {
      word: "niyanan",
      translation: "five (5)",
      language: "Cree",
      phonetic: "nee-YAN-an",
      meaning: "The number five",
      culturalContext: "Fifth number. Often associated with the hand (five fingers).",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'naanan'. Hand-based counting system.",
    },
    {
      word: "nikotwasik",
      translation: "six (6)",
      language: "Cree",
      phonetic: "nik-OT-was-ik",
      meaning: "The number six",
      culturalContext: "Sixth number in the counting sequence.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'ningodwaaswi'.",
    },
    {
      word: "tepakohp",
      translation: "seven (7)",
      language: "Cree",
      phonetic: "TEP-a-kohp",
      meaning: "The number seven - often associated with spiritual teachings",
      culturalContext: "Seven is significant in many teachings, including the Seven Grandfather Teachings.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Seven has ceremonial significance across many Indigenous cultures.",
    },
    {
      word: "ayinanew",
      translation: "eight (8)",
      language: "Cree",
      phonetic: "ay-in-AN-ew",
      meaning: "The number eight",
      culturalContext: "Eighth number in the counting sequence.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate forms across Algonquin languages.",
    },
    {
      word: "kekamitataht",
      translation: "nine (9)",
      language: "Cree",
      phonetic: "kek-a-MIT-a-taht",
      meaning: "The number nine - almost ten",
      culturalContext: "Ninth number. Structure often means 'almost ten'.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Constructed as 'nearly ten' in many Algonquin languages.",
    },
    {
      word: "mitataht",
      translation: "ten (10)",
      language: "Cree",
      phonetic: "mit-AT-aht",
      meaning: "The number ten",
      culturalContext: "Base of the counting system. Larger numbers build on ten.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'midaaswi'. Proto-Algonquian *metathswi.",
    },

    // NATURE AND WEATHER - CREE
    {
      word: "pisim",
      translation: "sun / moon / month",
      language: "Cree",
      phonetic: "PIS-im",
      meaning: "The sun, moon, or a month - celestial body and time measurement",
      culturalContext: "The sun and moon govern time and seasons. Months are counted by moons.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Same word for sun and moon reflects their cyclical relationship.",
    },
    {
      word: "kimiwan",
      translation: "rain / it is raining",
      language: "Cree",
      phonetic: "kim-EE-wan",
      meaning: "Rain or the act of raining",
      culturalContext: "Rain is essential for life. Rain ceremonies were important for crops and hunting.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'gimiwan'. Common Algonquin weather verb.",
    },
    {
      word: "mispon",
      translation: "snow / it is snowing",
      language: "Cree",
      phonetic: "MIS-pon",
      meaning: "Snow or the act of snowing",
      culturalContext: "Snow determines winter activities - hunting, trapping, travel on snowshoes.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Multiple words for snow types exist. Mispon is general term.",
    },
    {
      word: "kistin",
      translation: "cold / it is cold",
      language: "Cree",
      phonetic: "KIS-tin",
      meaning: "Cold weather or being cold",
      culturalContext: "Cold survival knowledge was essential. Extended cold periods shaped culture.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Related to kistin (winter). Survival in cold was crucial.",
    },
    {
      word: "kisopwe",
      translation: "warm / it is warm",
      language: "Cree",
      phonetic: "KIS-op-way",
      meaning: "Warm or it is warm weather",
      culturalContext: "Warmth brings growth and movement. Summer was time for gathering.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Opposite of kistin. Describes comfortable temperature.",
    },
    {
      word: "yotin",
      translation: "wind / it is windy",
      language: "Cree",
      phonetic: "YOH-tin",
      meaning: "Wind or the condition of being windy",
      culturalContext: "Winds were associated with spirits. Different winds brought different weather.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Wind direction indicated weather changes. Important for travel.",
    },
    {
      word: "mikisow",
      translation: "eagle",
      language: "Cree",
      phonetic: "mik-IS-ow",
      meaning: "The eagle, a sacred messenger bird",
      culturalContext: "Eagles are sacred messengers between humans and the Creator. Eagle feathers are highly respected.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'migizi'. Eagle is spiritually central.",
    },
    {
      word: "omakakis",
      translation: "frog",
      language: "Cree",
      phonetic: "oh-MAK-ak-is",
      meaning: "The frog, associated with rain and water",
      culturalContext: "Frogs are connected to rain and water. Their songs herald spring.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Frogs appear in stories about water and rain.",
    },
    {
      word: "kahkakiw",
      translation: "raven / crow",
      language: "Cree",
      phonetic: "KAH-kak-iw",
      meaning: "The raven or crow, a trickster figure",
      culturalContext: "Ravens are clever and appear in trickster stories. They are survivors and adapters.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Onomatopoeic origin from the bird's call.",
    },
    {
      word: "okimaw",
      translation: "chief / leader",
      language: "Cree",
      phonetic: "oh-KIM-aw",
      meaning: "A chief or leader - one who leads the people",
      culturalContext: "Chiefs earned leadership through wisdom and action, not inheritance. Consensus was important.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Also root of 'okimakan' (chief made by others). Leadership was earned.",
    },
    {
      word: "iskwew",
      translation: "woman",
      language: "Cree",
      phonetic: "IS-kwew",
      meaning: "A woman - respected role in Cree society",
      culturalContext: "Women were respected as life-givers and keepers of water. Matrilineal influences existed.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Women held significant spiritual and practical roles in Cree society.",
    },
    {
      word: "napew",
      translation: "man",
      language: "Cree",
      phonetic: "NAP-ew",
      meaning: "A man - adult male",
      culturalContext: "Men had specific responsibilities including hunting and protection.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate forms across Algonquin languages for adult male.",
    },
    {
      word: "awasis",
      translation: "child",
      language: "Cree",
      phonetic: "AW-as-is",
      meaning: "A child - young person",
      culturalContext: "Children are sacred gifts. They were raised by the whole community.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Children were highly valued and carefully taught traditions.",
    },
    {
      word: "kokom",
      translation: "grandmother",
      language: "Cree",
      phonetic: "KOH-kom",
      meaning: "Grandmother - respected elder",
      culturalContext: "Grandmothers are primary teachers of traditions. They hold great respect.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Grandparents were primary teachers. Kokom stories are treasured.",
    },
    {
      word: "mosom",
      translation: "grandfather",
      language: "Cree",
      phonetic: "MOH-som",
      meaning: "Grandfather - respected elder",
      culturalContext: "Grandfathers taught hunting, storytelling, and spiritual practices.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Elders are repositories of knowledge and history.",
    },
    {
      word: "asikan",
      translation: "stocking / sock / moccasin liner",
      language: "Cree",
      phonetic: "AS-ik-an",
      meaning: "Sock or moccasin liner for warmth",
      culturalContext: "Proper footwear was essential for survival. Liners added warmth and comfort.",
      category: "trading",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Fur trade posts traded cloth and wool for making warm footwear liners.",
    },
    {
      word: "asiniy",
      translation: "stone / rock",
      language: "Cree",
      phonetic: "AS-in-ee",
      meaning: "A stone or rock",
      culturalContext: "Stones were used for tools, ceremonies, and as landmarks. Grandfather stones are used in sweats.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'asin'. Proto-Algonquian root for stone.",
    },
    {
      word: "sakaw",
      translation: "forest / bush / wilderness",
      language: "Cree",
      phonetic: "SAK-aw",
      meaning: "The forest or bush country",
      culturalContext: "The boreal forest was home. Sakaw provides shelter, food, medicine, and materials.",
      category: "geography",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "The bush was home territory. Knowing the sakaw was essential.",
    },
    {
      word: "maskihkiy",
      translation: "medicine / herbs",
      language: "Cree",
      phonetic: "musk-IH-kee",
      meaning: "Medicine, including medicinal plants and spiritual healing",
      culturalContext: "Traditional medicine encompasses plants, ceremonies, and spiritual practices. Knowledge passed down carefully.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'mashkiki'. Sacred knowledge carefully guarded.",
    },
    {
      word: "asam",
      translation: "snowshoe",
      language: "Cree",
      phonetic: "AS-am",
      meaning: "Snowshoe for walking on snow",
      culturalContext: "Snowshoes were essential technology for winter travel. Different styles for different snow conditions.",
      category: "trading",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Snowshoe technology allowed travel across deep snow. Revolutionary for winter hunting.",
    },
    {
      word: "ciman",
      translation: "canoe",
      language: "Cree",
      phonetic: "CHIM-an",
      meaning: "A canoe - the essential watercraft",
      culturalContext: "Birch bark canoes were the transportation technology that enabled the fur trade.",
      category: "waterway",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Ojibwe 'jiimaan'. Canoe technology was adopted by traders.",
    },
    {
      word: "otapanask",
      translation: "sled / toboggan",
      language: "Cree",
      phonetic: "ot-AP-an-ask",
      meaning: "A toboggan or sled for winter travel",
      culturalContext: "Toboggans hauled goods and families across snow. Essential for winter camps.",
      category: "trading",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "English 'toboggan' derived from Algonquin languages. Winter transport.",
    },
    {
      word: "pahkwesikan",
      translation: "bannock / bread",
      language: "Cree",
      phonetic: "pah-KWES-ik-an",
      meaning: "Bread or bannock - adopted during fur trade era",
      culturalContext: "Bannock became a staple food during the fur trade, made from traded flour.",
      category: "trading",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Shows cultural adaptation. Bannock became 'traditional' after European contact.",
    },

    // ==================== OJIBWE/ANISHINAABE (ALGONQUIN FAMILY) ====================
    // Target: 40+ entries

    // CONVERSATIONAL PHRASES - OJIBWE
    {
      word: "aaniin",
      translation: "hello / how are you",
      language: "Ojibwe",
      phonetic: "AH-neen",
      meaning: "Hello or how are you - common greeting",
      culturalContext: "Standard Ojibwe greeting. Shows interest in the person's wellbeing.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'tanisi'. Different Algonquin greeting forms.",
    },
    {
      word: "miigwech",
      translation: "thank you",
      language: "Ojibwe",
      phonetic: "MEE-gwech",
      meaning: "Thank you - expression of gratitude",
      culturalContext: "Gratitude is central to Ojibwe values. Miigwech acknowledges gifts and kindness.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "One of the most commonly used Ojibwe words. Shows appreciation.",
    },
    {
      word: "eya",
      translation: "yes",
      language: "Ojibwe",
      phonetic: "AY-yah",
      meaning: "Yes - affirmative response",
      culturalContext: "Simple affirmative. Used to agree or confirm.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'ehe'. Common Algonquin affirmative pattern.",
    },
    {
      word: "gaawiin",
      translation: "no",
      language: "Ojibwe",
      phonetic: "GAH-ween",
      meaning: "No - negative response",
      culturalContext: "Negative response. Can also be used to negate verbs.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'namoya'. Negative particle.",
    },
    {
      word: "giga-waabamin",
      translation: "goodbye / see you later",
      language: "Ojibwe",
      phonetic: "gig-ah-WAH-bam-in",
      meaning: "I will see you - used as goodbye",
      culturalContext: "A hopeful farewell implying future meeting. Not final goodbye.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Literally 'I will see you'. Implies continued relationship.",
    },
    {
      word: "boozhoo",
      translation: "hello / greetings",
      language: "Ojibwe",
      phonetic: "BOO-zhoo",
      meaning: "Hello - common greeting",
      culturalContext: "Widely used greeting. Some believe it derives from the French 'bonjour' while others cite Indigenous origins.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Debated etymology. May be from 'Nanabozho' the trickster or from French 'bonjour'.",
    },
    {
      word: "nindizhinikaaz",
      translation: "my name is...",
      language: "Ojibwe",
      phonetic: "nin-diz-in-IK-ahz",
      meaning: "I am called... - introducing yourself",
      culturalContext: "Names are significant in Ojibwe culture. Spirit names are given through ceremony.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Nind- is first person prefix. -izhinikaaz means 'to be named'.",
    },
    {
      word: "aaniin ezhinikaazyan",
      translation: "what is your name?",
      language: "Ojibwe",
      phonetic: "AH-neen ezh-in-IK-ahz-yan",
      meaning: "What are you called? - asking someone's name",
      culturalContext: "Polite way to learn someone's name. Shows interest in the person.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Aaniin (what/how) + ezhinikaazyan (you are called).",
    },
    {
      word: "niijii",
      translation: "friend",
      language: "Ojibwe",
      phonetic: "NEE-jee",
      meaning: "Friend - term of friendly address",
      culturalContext: "Friendship bonds are important. Niijii implies mutual respect and care.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'nitotema'. Friend terms show relationship importance.",
    },
    {
      word: "biindigen",
      translation: "come in / welcome",
      language: "Ojibwe",
      phonetic: "BEEN-dig-en",
      meaning: "Come inside - welcoming someone",
      culturalContext: "Hospitality is valued. Visitors are welcomed and fed.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Imperative form. Ojibwe hospitality traditions run deep.",
    },
    {
      word: "aaniish na",
      translation: "how are you? / what's up?",
      language: "Ojibwe",
      phonetic: "AH-neesh nah",
      meaning: "How are you doing? - casual check-in",
      culturalContext: "Casual greeting asking about wellbeing. Shows care for the person.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "More casual than formal aaniin. Na is question particle.",
    },
    {
      word: "mino-gizheb",
      translation: "good morning",
      language: "Ojibwe",
      phonetic: "min-oh-GIZH-eb",
      meaning: "Good morning - morning greeting",
      culturalContext: "Morning greeting. Each part of day acknowledged differently.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Mino (good) + gizheb (morning). Time-specific greeting.",
    },
    {
      word: "mino-naawakwe",
      translation: "good afternoon",
      language: "Ojibwe",
      phonetic: "min-oh-NAH-wak-way",
      meaning: "Good afternoon - midday greeting",
      culturalContext: "Afternoon greeting. Shows awareness of time passing.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Naawakwe refers to midday/afternoon period.",
    },
    {
      word: "mino-onaagoshig",
      translation: "good evening",
      language: "Ojibwe",
      phonetic: "min-oh-on-AH-go-shig",
      meaning: "Good evening - evening greeting",
      culturalContext: "Evening greeting. Evening was time for stories and gathering.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Onaagoshig means evening time.",
    },
    {
      word: "aandi",
      translation: "where",
      language: "Ojibwe",
      phonetic: "AHN-dee",
      meaning: "Where - location question word",
      culturalContext: "Used to ask about places. Geographic knowledge was essential.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Question word for location. Compare to Cree 'tanta'.",
    },

    // NUMBERS - OJIBWE
    {
      word: "bezhig",
      translation: "one (1)",
      language: "Ojibwe",
      phonetic: "BEZH-ig",
      meaning: "The number one",
      culturalContext: "First number. Also means 'alone' or 'only one'.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'peyak'. Proto-Algonquian number.",
    },
    {
      word: "niizh",
      translation: "two (2)",
      language: "Ojibwe",
      phonetic: "NEEZH",
      meaning: "The number two",
      culturalContext: "Second number. Pairs and duality have significance.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'niso'. Common Algonquin root.",
    },
    {
      word: "niswi",
      translation: "three (3)",
      language: "Ojibwe",
      phonetic: "NIS-wee",
      meaning: "The number three",
      culturalContext: "Third number. Three appears in many teachings.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'nisto'. Proto-Algonquian *neswa.",
    },
    {
      word: "niiwin",
      translation: "four (4)",
      language: "Ojibwe",
      phonetic: "NEE-win",
      meaning: "The number four - sacred number",
      culturalContext: "Four is sacred - four directions, four seasons, four elements. Central to ceremony.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'newo'. Four is spiritually significant.",
    },
    {
      word: "naanan",
      translation: "five (5)",
      language: "Ojibwe",
      phonetic: "NAH-nan",
      meaning: "The number five",
      culturalContext: "Fifth number. Associated with the hand.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'niyanan'. Hand-based counting.",
    },
    {
      word: "ningodwaaswi",
      translation: "six (6)",
      language: "Ojibwe",
      phonetic: "ning-od-WAHS-wee",
      meaning: "The number six",
      culturalContext: "Sixth number in counting sequence.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'nikotwasik'.",
    },
    {
      word: "niizhwaaswi",
      translation: "seven (7)",
      language: "Ojibwe",
      phonetic: "NEEZH-wahs-wee",
      meaning: "The number seven - Seven Grandfather Teachings",
      culturalContext: "Seven is significant for the Seven Grandfather Teachings: love, respect, bravery, truth, honesty, humility, wisdom.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Seven Grandfather Teachings are core Ojibwe values.",
    },
    {
      word: "nishwaaswi",
      translation: "eight (8)",
      language: "Ojibwe",
      phonetic: "nish-WAHS-wee",
      meaning: "The number eight",
      culturalContext: "Eighth number in counting sequence.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'ayinanew'.",
    },
    {
      word: "zhaangaswi",
      translation: "nine (9)",
      language: "Ojibwe",
      phonetic: "ZHAHN-gas-wee",
      meaning: "The number nine",
      culturalContext: "Ninth number. Means 'almost ten'.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Constructed as 'nearly ten'.",
    },
    {
      word: "midaaswi",
      translation: "ten (10)",
      language: "Ojibwe",
      phonetic: "mid-AHS-wee",
      meaning: "The number ten",
      culturalContext: "Base of counting system. Ten fingers.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'mitataht'. Proto-Algonquian root.",
    },

    // NATURE AND CULTURE - OJIBWE
    {
      word: "giizis",
      translation: "sun / moon / month",
      language: "Ojibwe",
      phonetic: "GEE-zis",
      meaning: "The sun, moon, or a month",
      culturalContext: "Celestial bodies mark time. Months are counted by moons.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'pisim'. Same word for sun/moon common in Algonquin.",
    },
    {
      word: "anang",
      translation: "star",
      language: "Ojibwe",
      phonetic: "AN-ang",
      meaning: "A star - celestial body",
      culturalContext: "Stars guided navigation. Star stories taught values and history.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Stars provided navigation. Winter stars especially visible.",
    },
    {
      word: "migizi",
      translation: "eagle",
      language: "Ojibwe",
      phonetic: "mig-IZ-ee",
      meaning: "The bald eagle - sacred messenger",
      culturalContext: "Eagles carry prayers to the Creator. Eagle feathers are sacred.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'mikisow'. Eagle is spiritually central.",
    },
    {
      word: "miskwaadesi",
      translation: "turtle",
      language: "Ojibwe",
      phonetic: "misk-WAH-des-ee",
      meaning: "The turtle - Turtle Island",
      culturalContext: "North America is Turtle Island in Ojibwe cosmology. Turtle Clan is one of the original clans.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Turtle Island creation story is fundamental to Ojibwe worldview.",
    },
    {
      word: "ma'iingan",
      translation: "wolf",
      language: "Ojibwe",
      phonetic: "mah-EEN-gan",
      meaning: "The wolf - companion animal",
      culturalContext: "Wolf was the first animal to befriend humans in Ojibwe stories. Wolf Clan is a leading clan.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'mahihkan'. Wolf clan provides leadership.",
    },
    {
      word: "wazhashk",
      translation: "muskrat",
      language: "Ojibwe",
      phonetic: "WAZH-ashk",
      meaning: "The muskrat - Earth-Diver hero",
      culturalContext: "In the Earth-Diver story, muskrat successfully brought up earth to create land.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'wacask'. Hero of creation story.",
    },
    {
      word: "ogimaa",
      translation: "chief / leader",
      language: "Ojibwe",
      phonetic: "oh-GIM-ah",
      meaning: "A chief or leader",
      culturalContext: "Leadership was earned through wisdom and service. Chiefs led by consensus.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'okimaw'. Leadership through service.",
    },
    {
      word: "ikwe",
      translation: "woman",
      language: "Ojibwe",
      phonetic: "IK-way",
      meaning: "A woman - respected life-giver",
      culturalContext: "Women are life-givers and water keepers. Matrilineal elements in society.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'iskwew'. Women held respected roles.",
    },
    {
      word: "inini",
      translation: "man",
      language: "Ojibwe",
      phonetic: "IN-in-ee",
      meaning: "A man - adult male",
      culturalContext: "Men had responsibilities including hunting and protection.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Cognate with Cree 'napew'. Adult male term.",
    },
    {
      word: "abinoojii",
      translation: "child",
      language: "Ojibwe",
      phonetic: "ab-in-OO-jee",
      meaning: "A child - young person",
      culturalContext: "Children are sacred gifts. Community responsibility to teach them.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Children raised by extended family and community.",
    },
    {
      word: "nookomis",
      translation: "grandmother",
      language: "Ojibwe",
      phonetic: "noo-KOM-is",
      meaning: "Grandmother - respected elder",
      culturalContext: "Grandmothers are primary teachers. Nookomis stories transmit culture.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'kokom'. Grandparents are teachers.",
    },
    {
      word: "mishomis",
      translation: "grandfather",
      language: "Ojibwe",
      phonetic: "mish-OM-is",
      meaning: "Grandfather - respected elder",
      culturalContext: "Grandfathers teach stories, hunting, and spiritual practices.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'mosom'. Elders are respected teachers.",
    },
    {
      word: "doodem",
      translation: "clan / totem",
      language: "Ojibwe",
      phonetic: "DOH-dem",
      meaning: "Clan or totem - family group identity",
      culturalContext: "Clan system organizes society. You cannot marry within your clan.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Origin of English word 'totem'. Clan identity is fundamental.",
    },
    {
      word: "midewiwin",
      translation: "Grand Medicine Society",
      language: "Ojibwe",
      phonetic: "mid-AY-wee-win",
      meaning: "The Grand Medicine Society - traditional spiritual organization",
      culturalContext: "The Midewiwin preserves sacred teachings, ceremonies, and healing knowledge.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Sacred society maintaining spiritual teachings through birch bark scrolls.",
    },

    // ==================== DENE/CHIPEWYAN (ATHAPASKAN FAMILY) ====================
    // Target: 25+ entries

    // CONVERSATIONAL PHRASES - DENE
    {
      word: "edlanete",
      translation: "hello / how are you",
      language: "Dene",
      phonetic: "ed-LAN-eh-tay",
      meaning: "Hello or how are you - greeting",
      culturalContext: "Standard Dene greeting. Shows care for the person's wellbeing.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Athapaskan greeting patterns differ from Algonquin languages.",
    },
    {
      word: "mahsi",
      translation: "thank you",
      language: "Dene",
      phonetic: "MAH-see",
      meaning: "Thank you - gratitude expression",
      culturalContext: "Expressing gratitude is important. Mahsi shows appreciation.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Common across several Dene languages. Short form used frequently.",
    },
    {
      word: "mahsi cho",
      translation: "thank you very much",
      language: "Dene",
      phonetic: "MAH-see CHO",
      meaning: "Thank you very much - emphatic gratitude",
      culturalContext: "Cho means big/great. Mahsi cho is emphatic thanks.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Cho intensifies the thanks. Great gratitude.",
    },
    {
      word: "eyi",
      translation: "yes",
      language: "Dene",
      phonetic: "AY-yee",
      meaning: "Yes - affirmative",
      culturalContext: "Simple affirmative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Athapaskan affirmative differs from Algonquin patterns.",
    },
    {
      word: "ileh",
      translation: "no",
      language: "Dene",
      phonetic: "IL-eh",
      meaning: "No - negative response",
      culturalContext: "Negative response to questions.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Athapaskan negative particle.",
    },
    {
      word: "setth'i heli",
      translation: "my name is...",
      language: "Dene",
      phonetic: "seth-ee HEL-ee",
      meaning: "My name is called... - introduction",
      culturalContext: "Personal names were important and sometimes changed with life events.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Self-introduction pattern in Dene languages.",
    },
    {
      word: "netth'i",
      translation: "your name",
      language: "Dene",
      phonetic: "neth-EE",
      meaning: "Your name - used in asking names",
      culturalContext: "Used to ask someone's name politely.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Second person possession marker.",
    },
    {
      word: "seli",
      translation: "friend",
      language: "Dene",
      phonetic: "SEL-ee",
      meaning: "Friend - term of friendship",
      culturalContext: "Friendship implied mutual aid and respect.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Friend terms show relationship importance.",
    },

    // NUMBERS - DENE
    {
      word: "t'akui",
      translation: "one (1)",
      language: "Dene",
      phonetic: "tah-KWEE",
      meaning: "The number one",
      culturalContext: "First number in counting.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Athapaskan number system distinct from Algonquin.",
    },
    {
      word: "nake",
      translation: "two (2)",
      language: "Dene",
      phonetic: "NAH-kay",
      meaning: "The number two",
      culturalContext: "Second number in counting sequence.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Related to Navajo 'naaki'. Athapaskan cognate.",
    },
    {
      word: "thai",
      translation: "three (3)",
      language: "Dene",
      phonetic: "THIGH",
      meaning: "The number three",
      culturalContext: "Third number. Three has significance in stories.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Athapaskan three differs from Algonquin 'nisto/niswi'.",
    },
    {
      word: "dinki",
      translation: "four (4)",
      language: "Dene",
      phonetic: "DIN-kee",
      meaning: "The number four",
      culturalContext: "Four directions have significance.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Compare to Navajo 'dii'. Athapaskan root for four.",
    },
    {
      word: "sesonlai",
      translation: "five (5)",
      language: "Dene",
      phonetic: "ses-ON-lye",
      meaning: "The number five",
      culturalContext: "Fifth number. Hand-based counting.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Often means 'my hand' or 'five fingers'.",
    },

    // NATURE AND GEOGRAPHY - DENE
    {
      word: "sa",
      translation: "sun",
      language: "Dene",
      phonetic: "SAH",
      meaning: "The sun",
      culturalContext: "Sun provides light and warmth. Crucial in far north.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Related to Navajo 'shaa'. Athapaskan sun word.",
    },
    {
      word: "tth'i",
      translation: "moon",
      language: "Dene",
      phonetic: "TH-ee",
      meaning: "The moon",
      culturalContext: "Moon governs time and tides. Months measured by moons.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Separate word from sun, unlike some Algonquin languages.",
    },
    {
      word: "nidhe",
      translation: "land / earth",
      language: "Dene",
      phonetic: "NID-hay",
      meaning: "The land or earth",
      culturalContext: "Land is sacred and alive. Dene are people of the land.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Root appears in Denendeh (land of the people).",
    },
    {
      word: "gah",
      translation: "rabbit / hare",
      language: "Dene",
      phonetic: "GAH",
      meaning: "The snowshoe hare",
      culturalContext: "Rabbits were important food, especially in lean times. Rabbit snares common.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Compare to Navajo 'gah'. Pan-Athapaskan root for rabbit.",
    },
    {
      word: "tsa",
      translation: "bear",
      language: "Dene",
      phonetic: "TSAH",
      meaning: "The bear",
      culturalContext: "Bears are powerful and respected. Special protocols when encountering bears.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Different from Algonquin 'maskwa/makwa'. Athapaskan root.",
    },
    {
      word: "nogha",
      translation: "wolverine",
      language: "Dene",
      phonetic: "NOH-gah",
      meaning: "The wolverine - fierce and solitary",
      culturalContext: "Wolverine fur was prized for parka ruffs because frost brushes off easily.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Wolverine important for cold-weather clothing.",
    },
    {
      word: "lue",
      translation: "fish",
      language: "Dene",
      phonetic: "LOO-ay",
      meaning: "Fish - general term",
      culturalContext: "Fish were crucial food, especially lake trout and whitefish.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Fish camps were important seasonal gatherings.",
    },
    {
      word: "sas",
      translation: "black bear",
      language: "Dene",
      phonetic: "SAHS",
      meaning: "The black bear specifically",
      culturalContext: "Black bears encountered in forest areas. Different protocols than grizzly.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Dene distinguish between bear species with different terms.",
    },
    {
      word: "tseli",
      translation: "firewood",
      language: "Dene",
      phonetic: "TSEL-ee",
      meaning: "Wood for fire",
      culturalContext: "Fire was essential for survival. Gathering firewood was daily work.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ATHAPASKAN,
      linguisticNotes: "Fire knowledge crucial in subarctic environment.",
    },

    // ==================== BLACKFOOT/SIKSIKA (ALGONQUIN FAMILY) ====================
    // Target: 25+ entries

    // CONVERSATIONAL PHRASES - BLACKFOOT
    {
      word: "oki",
      translation: "hello",
      language: "Blackfoot",
      phonetic: "OH-kee",
      meaning: "Hello - standard greeting",
      culturalContext: "Common greeting. Also means spirit or supernatural being.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Spiritual concept embedded in daily greeting.",
    },
    {
      word: "iihtsipaistapiiyi'pa",
      translation: "thank you",
      language: "Blackfoot",
      phonetic: "eet-sip-ais-TAP-ee-yi-pa",
      meaning: "Thank you - expression of gratitude",
      culturalContext: "Formal thanks. Gratitude important in Blackfoot values.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Complex word structure typical of Blackfoot.",
    },
    {
      word: "aahsaapinakos",
      translation: "goodbye / see you later",
      language: "Blackfoot",
      phonetic: "ah-SAH-pin-ah-kos",
      meaning: "Goodbye - departing words",
      culturalContext: "Parting greeting implying future meeting.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Not a final goodbye, implies continued relationship.",
    },
    {
      word: "aa",
      translation: "yes",
      language: "Blackfoot",
      phonetic: "AH",
      meaning: "Yes - affirmative",
      culturalContext: "Simple affirmative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Short affirmative common in conversation.",
    },
    {
      word: "saa",
      translation: "no",
      language: "Blackfoot",
      phonetic: "SAH",
      meaning: "No - negative response",
      culturalContext: "Negative response to questions.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Blackfoot negative particle.",
    },
    {
      word: "nitsiniiyi'taki",
      translation: "my name is...",
      language: "Blackfoot",
      phonetic: "nit-sin-ee-YI-tak-ee",
      meaning: "I am called... - introduction",
      culturalContext: "Names had spiritual significance. Earned names common.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Nit- is first person prefix in Blackfoot.",
    },
    {
      word: "tsa niitapi'tsiniiyaawa",
      translation: "what is your name?",
      language: "Blackfoot",
      phonetic: "TSA neet-AP-i-tsin-ee-YAH-wa",
      meaning: "What are you called?",
      culturalContext: "Polite way to ask someone's name.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Tsa means 'what'. Question formation in Blackfoot.",
    },
    {
      word: "niikso'kowai'taman",
      translation: "friend",
      language: "Blackfoot",
      phonetic: "neek-so-ko-WY-tam-an",
      meaning: "Friend - term of friendship",
      culturalContext: "Friendship bonds were serious commitments.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Complex word reflecting importance of friendship.",
    },
    {
      word: "aistsimoyihkaan",
      translation: "welcome / come in",
      language: "Blackfoot",
      phonetic: "aist-sim-oy-IH-kahn",
      meaning: "Welcome - inviting someone in",
      culturalContext: "Hospitality was important. Visitors were fed.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Invitation to enter one's tipi or home.",
    },
    {
      word: "iiksistsikomi",
      translation: "good morning",
      language: "Blackfoot",
      phonetic: "eek-sis-TSIK-om-ee",
      meaning: "Good morning greeting",
      culturalContext: "Morning greetings acknowledge the new day.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Time-specific greeting in Blackfoot.",
    },

    // NUMBERS - BLACKFOOT
    {
      word: "nitaka",
      translation: "one (1)",
      language: "Blackfoot",
      phonetic: "nit-AH-ka",
      meaning: "The number one",
      culturalContext: "First number in Blackfoot counting.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Blackfoot numbers distinct from eastern Algonquin.",
    },
    {
      word: "natoka",
      translation: "two (2)",
      language: "Blackfoot",
      phonetic: "nat-OH-ka",
      meaning: "The number two",
      culturalContext: "Second number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Blackfoot number system developed independently.",
    },
    {
      word: "noohka",
      translation: "three (3)",
      language: "Blackfoot",
      phonetic: "NOOH-ka",
      meaning: "The number three",
      culturalContext: "Third number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Three has significance in stories.",
    },
    {
      word: "niiso",
      translation: "four (4)",
      language: "Blackfoot",
      phonetic: "NEE-so",
      meaning: "The number four - sacred number",
      culturalContext: "Four is sacred - four directions, four seasons. Central to Blackfoot spirituality.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Four directions fundamental to worldview.",
    },
    {
      word: "niisito",
      translation: "five (5)",
      language: "Blackfoot",
      phonetic: "nee-SIT-oh",
      meaning: "The number five",
      culturalContext: "Fifth number. Hand-based counting.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Five associated with the hand.",
    },

    // NATURE AND CULTURE - BLACKFOOT
    {
      word: "natosi",
      translation: "sun",
      language: "Blackfoot",
      phonetic: "nat-OH-see",
      meaning: "The sun - sacred life-giver",
      culturalContext: "The Sun is central to Blackfoot spirituality. Sun Dance is the most important ceremony.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Sun Dance (Okan) is the central Blackfoot ceremony.",
    },
    {
      word: "ko'komiki'somm",
      translation: "moon",
      language: "Blackfoot",
      phonetic: "ko-kom-IK-ee-som",
      meaning: "The moon",
      culturalContext: "Moon governs women's ceremonies and time-keeping.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Moon connected to feminine power in Blackfoot belief.",
    },
    {
      word: "omahkapi'si",
      translation: "big dog / horse",
      language: "Blackfoot",
      phonetic: "oh-MAH-kap-ee-see",
      meaning: "Horse - literally 'big dog' or 'elk-dog'",
      culturalContext: "Horses transformed Blackfoot life. They became renowned horsemen.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "New word created for horses. Dogs were previous transport animals.",
    },
    {
      word: "pitaikiimm",
      translation: "eagle",
      language: "Blackfoot",
      phonetic: "pit-EYE-keem",
      meaning: "The eagle - sacred messenger",
      culturalContext: "Eagles are sacred. Eagle feathers used in ceremony.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Eagle trapping was sacred practice with specific protocols.",
    },
    {
      word: "ksistsikum",
      translation: "river",
      language: "Blackfoot",
      phonetic: "KSIS-tsik-um",
      meaning: "A river",
      culturalContext: "Rivers like the Bow and Oldman were lifelines on the prairies.",
      category: "waterway",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Different root than Cree/Ojibwe 'sipiy/ziibi'.",
    },
    {
      word: "omoxtokiyit",
      translation: "water",
      language: "Blackfoot",
      phonetic: "oh-mox-TOH-kee-yit",
      meaning: "Water",
      culturalContext: "Water was precious on the prairies. Rivers and springs were vital.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Distinct from eastern Algonquin 'nipiy/nibi'.",
    },
    {
      word: "niitawahsin",
      translation: "my land / my territory",
      language: "Blackfoot",
      phonetic: "nee-tah-WAH-sin",
      meaning: "My land - expressing territorial connection",
      culturalContext: "The Blackfoot had defined territory on the northern plains.",
      category: "geography",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Territory was well-defined and defended.",
    },

    // ==================== INUKTITUT (ESKIMO-ALEUT FAMILY) ====================
    // Target: 25+ entries

    // CONVERSATIONAL PHRASES - INUKTITUT
    {
      word: "ai",
      translation: "hello / hi",
      language: "Inuktitut",
      phonetic: "EYE",
      meaning: "Hello - casual greeting",
      culturalContext: "Informal greeting among friends.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Short informal greeting. Longer forms exist for formal situations.",
    },
    {
      word: "atelihai",
      translation: "hello / greetings",
      language: "Inuktitut",
      phonetic: "at-eh-lee-HI",
      meaning: "Hello - friendly greeting (regional)",
      culturalContext: "Regional greeting form. Dialects vary across Inuit territories.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Inuktitut has dialectal variation across Arctic regions.",
    },
    {
      word: "nakurmiik",
      translation: "thank you",
      language: "Inuktitut",
      phonetic: "na-KOOR-meek",
      meaning: "Thank you - expression of gratitude",
      culturalContext: "Gratitude is important. Sharing was essential for Arctic survival.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Gratitude expressed frequently in culture of sharing.",
    },
    {
      word: "ii",
      translation: "yes",
      language: "Inuktitut",
      phonetic: "EE",
      meaning: "Yes - affirmative",
      culturalContext: "Simple affirmative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Short affirmative. Eyebrow raise also means yes.",
    },
    {
      word: "aakka",
      translation: "no",
      language: "Inuktitut",
      phonetic: "AHK-ka",
      meaning: "No - negative response",
      culturalContext: "Negative response. Nose wrinkle also means no.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Non-verbal communication (facial) also conveys yes/no.",
    },
    {
      word: "tavvauvutit",
      translation: "goodbye",
      language: "Inuktitut",
      phonetic: "tav-vow-VOO-tit",
      meaning: "Goodbye - farewell",
      culturalContext: "Parting greeting. Travel was dangerous in the Arctic.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Literally means 'that's it' or 'so be it'.",
    },
    {
      word: "kinauvit",
      translation: "who are you? / what is your name?",
      language: "Inuktitut",
      phonetic: "kin-OW-vit",
      meaning: "Who are you? - asking identity",
      culturalContext: "Names were important. People often had multiple names.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Kina (who) + -u- (to be) + -vit (you).",
    },
    {
      word: "uvanga",
      translation: "I / me",
      language: "Inuktitut",
      phonetic: "oo-VANG-a",
      meaning: "I or me - first person pronoun",
      culturalContext: "Self-reference. Used in introductions.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "First person pronoun. Uvanga + name for introduction.",
    },
    {
      word: "illu",
      translation: "friend / companion",
      language: "Inuktitut",
      phonetic: "IL-loo",
      meaning: "Friend - someone you share life with",
      culturalContext: "Friendship crucial for Arctic survival. Partners in hunting.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Friendship implied mutual obligation and sharing.",
    },
    {
      word: "qanuippit",
      translation: "how are you?",
      language: "Inuktitut",
      phonetic: "kan-oo-IP-pit",
      meaning: "How are you? - wellness check",
      culturalContext: "Checking on wellbeing. Health was precarious in Arctic conditions.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "From qanuq (how) + verb complex for being/doing.",
    },
    {
      word: "qanuinngittunga",
      translation: "I am fine",
      language: "Inuktitut",
      phonetic: "kan-oo-ING-it-tunga",
      meaning: "I am fine - response to how are you",
      culturalContext: "Standard response indicating wellbeing.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Literally 'I am not having anything wrong'.",
    },
    {
      word: "ublaakut",
      translation: "good morning",
      language: "Inuktitut",
      phonetic: "oob-LAH-koot",
      meaning: "Good morning - morning greeting",
      culturalContext: "Morning greeting. Daylight was precious in Arctic winter.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Ublaaq (morning) + suffix. Regional variations exist.",
    },
    {
      word: "unnukkut",
      translation: "good evening",
      language: "Inuktitut",
      phonetic: "oon-NOOK-koot",
      meaning: "Good evening - evening greeting",
      culturalContext: "Evening greeting. Evening was time for stories.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Unnuaq (evening) + suffix. Regional variations exist.",
    },
    {
      word: "naami",
      translation: "where",
      language: "Inuktitut",
      phonetic: "NAH-mee",
      meaning: "Where - location question",
      culturalContext: "Location knowledge crucial for Arctic navigation and hunting.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Question word for location. Essential for navigation.",
    },

    // NUMBERS - INUKTITUT
    {
      word: "atausiq",
      translation: "one (1)",
      language: "Inuktitut",
      phonetic: "at-OW-sik",
      meaning: "The number one",
      culturalContext: "First number. Traditional counting based on body parts.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Inuktitut counting traditionally used base-20 (fingers and toes).",
    },
    {
      word: "marruuk",
      translation: "two (2)",
      language: "Inuktitut",
      phonetic: "MAR-rook",
      meaning: "The number two",
      culturalContext: "Second number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Two - pairs important in Arctic (mittens, boots, partners).",
    },
    {
      word: "pingasut",
      translation: "three (3)",
      language: "Inuktitut",
      phonetic: "ping-A-soot",
      meaning: "The number three",
      culturalContext: "Third number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Three in Inuktitut counting sequence.",
    },
    {
      word: "sisamat",
      translation: "four (4)",
      language: "Inuktitut",
      phonetic: "sis-A-mat",
      meaning: "The number four",
      culturalContext: "Fourth number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Four in Inuktitut. Different from Algonquin 'newo/niiwin'.",
    },
    {
      word: "tallimat",
      translation: "five (5)",
      language: "Inuktitut",
      phonetic: "tal-LIM-at",
      meaning: "The number five",
      culturalContext: "Fifth number. Relates to hand/arm.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Related to talliq (arm). Hand-based counting.",
    },

    // NATURE - INUKTITUT
    {
      word: "aput",
      translation: "snow on ground",
      language: "Inuktitut",
      phonetic: "AP-oot",
      meaning: "Snow that has fallen and is on the ground",
      culturalContext: "Inuit have many words for snow. Aput is general snow on ground.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Famous for many snow words. Each describes specific conditions.",
    },
    {
      word: "qannik",
      translation: "falling snow",
      language: "Inuktitut",
      phonetic: "KAN-nik",
      meaning: "Snow that is currently falling",
      culturalContext: "Different word for falling vs. fallen snow reflects importance of snow conditions.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Precise snow terminology crucial for travel safety.",
    },
    {
      word: "piqsiq",
      translation: "blowing snow / blizzard",
      language: "Inuktitut",
      phonetic: "PIK-sik",
      meaning: "Snow blowing in the wind, blizzard conditions",
      culturalContext: "Blizzards were dangerous. Staying put essential during piqsiq.",
      category: "weather",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Blizzard conditions required shelter. Travel impossible.",
    },
    {
      word: "nattiq",
      translation: "ringed seal",
      language: "Inuktitut",
      phonetic: "NAT-tik",
      meaning: "The ringed seal - primary food source",
      culturalContext: "Ringed seals are the most important food animal. Every part used.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Ringed seal is the bread and butter of Inuit diet.",
    },
    {
      word: "aiviq",
      translation: "walrus",
      language: "Inuktitut",
      phonetic: "EYE-vik",
      meaning: "The walrus - important for food and materials",
      culturalContext: "Walrus provided meat, hide for boats, and ivory for tools.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Walrus hunting was communal and dangerous.",
    },
    {
      word: "arviq",
      translation: "bowhead whale",
      language: "Inuktitut",
      phonetic: "AR-vik",
      meaning: "The bowhead whale",
      culturalContext: "Bowhead whales provided enormous amounts of food and materials for communities.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Whale hunting was major communal event. One whale fed community.",
    },
    {
      word: "tiriganniaq",
      translation: "arctic fox",
      language: "Inuktitut",
      phonetic: "tir-ig-AN-ee-ak",
      meaning: "The arctic fox",
      culturalContext: "Arctic fox fur was valuable for trade. White fur prized.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Fox fur was major trade item with Hudson's Bay Company.",
    },
    {
      word: "ukpik",
      translation: "snowy owl",
      language: "Inuktitut",
      phonetic: "OOK-pik",
      meaning: "The snowy owl",
      culturalContext: "Snowy owls are iconic Arctic birds. Hunted for food and feathers.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Silent hunter of the Arctic. Symbol of the tundra.",
    },
    {
      word: "ulu",
      translation: "woman's knife",
      language: "Inuktitut",
      phonetic: "OO-loo",
      meaning: "Traditional curved knife used by women",
      culturalContext: "Essential tool for processing food, skins, and many tasks. Women's primary tool.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Iconic Inuit tool. Design unchanged for thousands of years.",
    },
    {
      word: "qulliq",
      translation: "oil lamp",
      language: "Inuktitut",
      phonetic: "KOO-lik",
      meaning: "Traditional soapstone oil lamp",
      culturalContext: "The qulliq provided heat and light. Women tended the lamp. Essential for survival.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ESKIMO_ALEUT,
      linguisticNotes: "Qulliq burning was women's responsibility. Symbol of home.",
    },

    // ==================== IROQUOIS/HAUDENOSAUNEE (IROQUOIAN FAMILY) ====================
    // Target: 20+ entries

    // CONVERSATIONAL PHRASES - MOHAWK
    {
      word: "she:kon",
      translation: "hello / greetings",
      language: "Mohawk",
      phonetic: "SHAY-gohn",
      meaning: "Hello - standard greeting",
      culturalContext: "Common Mohawk greeting. Literally means 'still, yet'.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Implies 'you are still alive' or 'peace still exists'. Acknowledges survival.",
    },
    {
      word: "nia:wen",
      translation: "thank you",
      language: "Mohawk",
      phonetic: "nee-AH-wen",
      meaning: "Thank you - expression of gratitude",
      culturalContext: "Gratitude is important in Haudenosaunee culture. Thanksgiving is central practice.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "The Thanksgiving Address is a central Haudenosaunee practice.",
    },
    {
      word: "hen",
      translation: "yes",
      language: "Mohawk",
      phonetic: "HEN",
      meaning: "Yes - affirmative",
      culturalContext: "Simple affirmative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Mohawk affirmative differs from Algonquin patterns.",
    },
    {
      word: "iah",
      translation: "no",
      language: "Mohawk",
      phonetic: "YAH",
      meaning: "No - negative response",
      culturalContext: "Negative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Mohawk negative particle.",
    },
    {
      word: "o:nen",
      translation: "goodbye / now",
      language: "Mohawk",
      phonetic: "OH-nen",
      meaning: "Goodbye or 'now' (at this time)",
      culturalContext: "Parting word. Also means 'now' in other contexts.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Multi-functional word used in farewells.",
    },
    {
      word: "nahoten esaiatats",
      translation: "what is your name?",
      language: "Mohawk",
      phonetic: "nah-HOH-ten es-eye-AT-ats",
      meaning: "What are you called?",
      culturalContext: "Asking someone's name. Names often earned through deeds.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Names could change through life events.",
    },
    {
      word: "iakatsiats",
      translation: "my name is...",
      language: "Mohawk",
      phonetic: "yak-at-SEE-ats",
      meaning: "I am called... - introduction",
      culturalContext: "Self-introduction. Names had meaning and power.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Name introduction in Mohawk.",
    },
    {
      word: "khale",
      translation: "and / also",
      language: "Mohawk",
      phonetic: "KHA-lay",
      meaning: "And or also - connector",
      culturalContext: "Used to connect ideas in conversation.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Common connector in speech.",
    },

    // NUMBERS - MOHAWK
    {
      word: "skaht",
      translation: "one (1)",
      language: "Mohawk",
      phonetic: "SKAHT",
      meaning: "The number one",
      culturalContext: "First number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Iroquoian numbers differ from Algonquin system.",
    },
    {
      word: "tekeni",
      translation: "two (2)",
      language: "Mohawk",
      phonetic: "tek-EN-ee",
      meaning: "The number two",
      culturalContext: "Second number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Mohawk counting sequence.",
    },
    {
      word: "ahsen",
      translation: "three (3)",
      language: "Mohawk",
      phonetic: "AH-sen",
      meaning: "The number three",
      culturalContext: "Third number. Three clans in Mohawk nation.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Three Mohawk clans: Bear, Wolf, Turtle.",
    },
    {
      word: "kaieri",
      translation: "four (4)",
      language: "Mohawk",
      phonetic: "ky-ER-ee",
      meaning: "The number four",
      culturalContext: "Fourth number.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Mohawk number four.",
    },
    {
      word: "wisk",
      translation: "five (5)",
      language: "Mohawk",
      phonetic: "WISK",
      meaning: "The number five",
      culturalContext: "Fifth number. Hand-based counting.",
      category: "number",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Five - one hand.",
    },

    // NATURE AND CULTURE - IROQUOIS/MOHAWK
    {
      word: "ohonti'a",
      translation: "corn",
      language: "Mohawk",
      phonetic: "oh-hon-TEE-ah",
      meaning: "Corn - one of the Three Sisters",
      culturalContext: "Corn, beans, and squash are the Three Sisters. Corn is central to Haudenosaunee agriculture.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Three Sisters agriculture sustained large populations.",
    },
    {
      word: "ohsaheta",
      translation: "beans",
      language: "Mohawk",
      phonetic: "oh-sah-HET-ah",
      meaning: "Beans - one of the Three Sisters",
      culturalContext: "Beans climb corn stalks and fix nitrogen. Part of Three Sisters agriculture.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Beans provided protein in the diet.",
    },
    {
      word: "onon'onsera",
      translation: "squash",
      language: "Mohawk",
      phonetic: "on-on-on-SER-ah",
      meaning: "Squash - one of the Three Sisters",
      culturalContext: "Squash leaves shade the ground, retaining moisture. Completes Three Sisters.",
      category: "nature",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Three Sisters planted together support each other.",
    },
    {
      word: "kanonhsesne",
      translation: "longhouse",
      language: "Mohawk",
      phonetic: "kan-on-SESS-nay",
      meaning: "Longhouse - traditional dwelling",
      culturalContext: "Longhouses housed extended families. Haudenosaunee means 'People of the Longhouse'.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Longhouse is symbol of Haudenosaunee Confederacy.",
    },
    {
      word: "roiane'shon'a",
      translation: "chiefs / leaders",
      language: "Mohawk",
      phonetic: "roy-yan-SHON-ah",
      meaning: "The chiefs or leaders",
      culturalContext: "Chiefs are chosen by clan mothers. Leadership through consensus.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Clan mothers select and can remove chiefs.",
    },
    {
      word: "iakonhsatste",
      translation: "clan mother",
      language: "Mohawk",
      phonetic: "yak-on-SAT-stay",
      meaning: "Clan mother - female leader",
      culturalContext: "Clan mothers hold significant power, including selecting chiefs.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Haudenosaunee society is matrilineal. Clan identity through mother.",
    },
    {
      word: "skennen",
      translation: "peace",
      language: "Mohawk",
      phonetic: "SKEN-nen",
      meaning: "Peace - central Haudenosaunee value",
      culturalContext: "The Great Law of Peace united the Six Nations. Peace is foundational.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Great Law of Peace predates European contact. Influenced US Constitution.",
    },
    {
      word: "kawennake",
      translation: "words / language",
      language: "Mohawk",
      phonetic: "ka-WEN-na-kay",
      meaning: "Words or language",
      culturalContext: "Language carries culture. Language revitalization is priority for Mohawk communities.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.IROQUOIAN,
      linguisticNotes: "Immersion schools work to revive Mohawk language.",
    },

    // ==================== MI'KMAQ (ALGONQUIN FAMILY) ====================
    // Target: 15+ entries

    // CONVERSATIONAL PHRASES - MI'KMAQ
    {
      word: "kwe",
      translation: "hello / hi",
      language: "Mi'kmaq",
      phonetic: "KWAY",
      meaning: "Hello - casual greeting",
      culturalContext: "Common Mi'kmaq greeting. Friendly and informal.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Short casual greeting similar to English 'hi'.",
    },
    {
      word: "wela'lin",
      translation: "thank you",
      language: "Mi'kmaq",
      phonetic: "wel-AH-lin",
      meaning: "Thank you - gratitude expression",
      culturalContext: "Gratitude shown for gifts, help, and sharing.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Similar to other Algonquin thanks forms.",
    },
    {
      word: "ehi",
      translation: "yes",
      language: "Mi'kmaq",
      phonetic: "AY-hee",
      meaning: "Yes - affirmative",
      culturalContext: "Simple affirmative response.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Compare to Cree 'ehe'. Algonquin affirmative pattern.",
    },
    {
      word: "moqwe",
      translation: "no",
      language: "Mi'kmaq",
      phonetic: "MOH-kway",
      meaning: "No - negative response",
      culturalContext: "Negative response to questions.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Mi'kmaq negative particle.",
    },
    {
      word: "nmultes",
      translation: "goodbye / see you",
      language: "Mi'kmaq",
      phonetic: "n-MOOL-tes",
      meaning: "Goodbye - parting words",
      culturalContext: "Farewell implying future meeting.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Not final goodbye, implies ongoing relationship.",
    },
    {
      word: "teluisi",
      translation: "my name is...",
      language: "Mi'kmaq",
      phonetic: "tel-OO-ee-see",
      meaning: "I am called... - introduction",
      culturalContext: "Self-introduction. Names were significant.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Name introduction in Mi'kmaq.",
    },
    {
      word: "nin",
      translation: "friend",
      language: "Mi'kmaq",
      phonetic: "NEEN",
      meaning: "Friend - term of friendship",
      culturalContext: "Friendship bonds were valued and maintained.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Short form for friend.",
    },

    // NATURE AND CULTURE - MI'KMAQ
    {
      word: "aqq",
      translation: "and",
      language: "Mi'kmaq",
      phonetic: "AHK",
      meaning: "And - connector",
      culturalContext: "Basic connector word in Mi'kmaq.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Common connector in speech.",
    },
    {
      word: "ta'n",
      translation: "where",
      language: "Mi'kmaq",
      phonetic: "TAHN",
      meaning: "Where - location question",
      culturalContext: "Used to ask about places.",
      category: "greeting",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Question word for location.",
    },
    {
      word: "mi'kmaki",
      translation: "Mi'kmaq territory / land of the Mi'kmaq",
      language: "Mi'kmaq",
      phonetic: "meeg-MAH-kee",
      meaning: "The traditional territory of the Mi'kmaq people",
      culturalContext: "Mi'kma'ki covers Atlantic Canada and parts of Maine. Never surrendered by treaty.",
      category: "geography",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Mi'kma'ki includes Nova Scotia, New Brunswick, PEI, Gaspe, Maine.",
    },
    {
      word: "msit no'kmaq",
      translation: "all my relations",
      language: "Mi'kmaq",
      phonetic: "m-SIT noh-KMAHK",
      meaning: "All my relations - acknowledging connection to all life",
      culturalContext: "Expresses kinship with all living things. Central to Mi'kmaq worldview.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Similar to Lakota 'mitakuye oyasin'. Universal interconnection.",
    },
    {
      word: "epekwitk",
      translation: "lying in the water / Prince Edward Island",
      language: "Mi'kmaq",
      phonetic: "EP-ek-witk",
      meaning: "Land lying in the water - PEI",
      culturalContext: "Mi'kmaq name for Prince Edward Island. Describes island geography.",
      category: "geography",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Descriptive place naming common in Mi'kmaq.",
    },
    {
      word: "kjipuktuk",
      translation: "great harbour / Halifax",
      language: "Mi'kmaq",
      phonetic: "jih-POOK-took",
      meaning: "The great harbour - Halifax Harbour",
      culturalContext: "Original Mi'kmaq name for Halifax area. Describes the harbour.",
      category: "geography",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Halifax sits on one of the world's largest natural harbours.",
    },
    {
      word: "pitu'paq",
      translation: "salmon",
      language: "Mi'kmaq",
      phonetic: "pit-OO-pak",
      meaning: "The Atlantic salmon",
      culturalContext: "Salmon were crucial food. Runs sustained communities for millennia.",
      category: "animal",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Atlantic salmon fishing rights remain important.",
    },
    {
      word: "kluscap",
      translation: "cultural hero / transformer",
      language: "Mi'kmaq",
      phonetic: "KLOOS-kap",
      meaning: "The culture hero who created and transformed the world",
      culturalContext: "Kluscap shaped the landscape and taught the Mi'kmaq. Central figure in stories.",
      category: "cultural",
      languageFamily: LANGUAGE_FAMILIES.ALGONQUIN,
      linguisticNotes: "Kluscap stories explain landscape features and cultural teachings.",
    },
  ];

  // Seed the words
  let addedCount = 0;
  for (const wordData of words) {
    // Create a unique ID based on language and word
    const wordId = `word_${wordData.language.toLowerCase().replace(/[^a-z]/g, '_')}_${wordData.word.replace(/[^a-zA-Z0-9]/g, '')}`;

    // Build the meaning string with linguistic notes if available
    let fullMeaning = wordData.meaning;
    if (wordData.linguisticNotes) {
      fullMeaning += ` [${wordData.linguisticNotes}]`;
    }

    // Build cultural context with language family info
    let fullContext = wordData.culturalContext;
    if (wordData.languageFamily) {
      fullContext = `[Language family: ${wordData.languageFamily}] ${fullContext}`;
    }

    await prisma.indigenousWord.upsert({
      where: { id: wordId },
      update: {
        word: wordData.word,
        translation: wordData.translation,
        language: wordData.language,
        phonetic: wordData.phonetic,
        meaning: fullMeaning,
        culturalContext: fullContext,
        category: wordData.category,
      },
      create: {
        id: wordId,
        word: wordData.word,
        translation: wordData.translation,
        language: wordData.language,
        phonetic: wordData.phonetic,
        meaning: fullMeaning,
        culturalContext: fullContext,
        category: wordData.category,
      },
    });
    addedCount++;
    if (addedCount % 25 === 0) {
      console.log(`  Processed ${addedCount} words...`);
    }
  }

  console.log(`\n  Total words processed: ${addedCount}`);

  // Print final counts
  console.log("\n==================== SEEDING COMPLETE ====================\n");

  const wordCount = await prisma.indigenousWord.count();

  // Count words by language
  const wordsByLanguage = await prisma.indigenousWord.groupBy({
    by: ['language'],
    _count: true,
    orderBy: { _count: { language: 'desc' } }
  });

  // Count words by category
  const wordsByCategory = await prisma.indigenousWord.groupBy({
    by: ['category'],
    _count: true,
    orderBy: { _count: { category: 'desc' } }
  });

  console.log("Final counts:");
  console.log(`  Total Indigenous words: ${wordCount}`);

  console.log("\nWords by language:");
  for (const group of wordsByLanguage) {
    console.log(`  ${group.language}: ${group._count} words`);
  }

  console.log("\nWords by category:");
  for (const group of wordsByCategory) {
    console.log(`  ${group.category || 'uncategorized'}: ${group._count} words`);
  }

  console.log("\nLanguage family distribution:");
  console.log("  Algonquin family: Cree, Ojibwe, Blackfoot, Mi'kmaq");
  console.log("  Athapaskan family: Dene/Chipewyan");
  console.log("  Iroquoian family: Mohawk/Iroquois");
  console.log("  Eskimo-Aleut family: Inuktitut");

  if (wordCount >= 200) {
    console.log("\n*** SUCCESS: Target of 200+ words achieved! ***");
  } else {
    console.log(`\n*** Note: Current count is ${wordCount}. Run additional seeds if needed. ***`);
  }
}

seedExpandedIndigenousWords()
  .catch((e) => {
    console.error("Error seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
